### ISSUE TITLE
Code sample for quick substring search in a large list of strings

### ISSUE THREAD

**Issue by KirillOsenkov** [Microsoft/elfie-arriba#160]
Hello folks!

I have a million strings (file paths) in an array. When user enters a search pattern I need to quickly display a list of all file paths from my array that have that search pattern as a substring. I only need the top N results.

What's the minimal code sample using Elfie to achieve my scenario? It's OK to take time to prepare any data structures in advance, but after that searches should be fast.

Thanks!

**Comment by dannychenmsft** [comment]
I don't know what the Elfie minimal version is.  But here's how to do it with Arriba.  I could compress a few lines if I wanted to get the minimum line count but I think this is good enough.  Actually, I would be super curious what the Elfie equivalent is.

`
        private static void SimpleStringTable()
        {
            const string cPath = "path";
            string[] cColumns = new string[] { cPath };

            string[] paths = new string[] { @"C:\test.txt", @"C:\TEMP\test.txt", @"C:\Foo\Bar\TEST.txt" };

            Table st = new Table("myTable", paths.Length);
            st.AddColumn(new ColumnDetails(cPath, "string", string.Empty, "s", true));
            DataBlock b = new DataBlock(cColumns, paths.Length);
            b.SetColumn(0, paths);
            st.AddOrUpdate(b);

            string searchVal = "TeSt";
            var result = st.Query(new SelectQuery(cColumns, null) { Where = SelectQuery.ParseWhere(cPath + ":=" + searchVal) });

            for (int i = 0; i < result.CountReturned; ++i)
            {
                Console.WriteLine("Match: {0}", result.Values[i, 0]);
            }
        }
`

**Comment by KirillOsenkov** [comment]
Perfect, thanks! Let me try that.

**Comment by vScottLouvau** [comment]
Hi, Kirill! Long time no see. =)


Searching paths in Elfie is more code, but should be a lot faster. I would probably convert the paths themselves to "String8", too, unless you need to keep them as .NET strings for another part of the code.


using System.IO;
using Microsoft.CodeAnalysis.Elfie.Model.Index;
using Microsoft.CodeAnalysis.Elfie.Model.Strings;
using Microsoft.CodeAnalysis.Elfie.Model.Structures;
using Microsoft.CodeAnalysis.Elfie.Serialization;
using System;

namespace PathSearch
{
    class PathFinder : IBinarySerializable
    {
        private StringStore Store { get; set; }
        private MemberIndex Index { get; set; }

        public PathFinder()
        {
            this.Store = new StringStore();
            this.Index = new MemberIndex();
        }

        /// <summary>
        ///  Build an index for each word in a set of file paths back to the index of the path in the array.
        /// </summary>
        /// <param name="paths">Array of string paths to index</param>
        public void IndexPathWords(string[] paths)
        {
            PartialArray<int> pathPartArray = new PartialArray<int>();
            byte[] buffer = new byte[1024];

            for(int pathIndex = 0; pathIndex < paths.Length; ++pathIndex)
            {
                // Convert the path to a String8 [UTF8 byte string]
                String8 path8 = String8.Convert(paths[pathIndex], buffer);

                // Split on '\' to get the path parts
                String8Set pathParts = path8.Split((byte)'\\', pathPartArray);

                // Index each part, pointing back to the index of the path in the array
                for(int i = 0; i < pathParts.Count; ++i)
                {
                    int wordIndex = this.Store.FindOrAddString(pathParts[i]);
                    this.Index.AddItem(wordIndex, pathIndex);
                }
            }
        }

        /// <summary>
        ///  Find the set of files with paths containing the word prefix typed.
        /// </summary>
        /// <param name="prefix">Word prefix of a path part</param>
        /// <param name="resultIndices">PartialArray to hold the desired number of matches</param>
        /// <returns>True if search had results, False otherwise</returns>
        public bool TryFind(string prefix, PartialArray<int> resultIndices)
        {
            // Ensure the Index is converted for search
            this.Index.ConvertToImmutable(this.Store);

            // Clear previous results
            resultIndices.Clear();

            // Look for all words starting with the value types
            Range matchingWords;
            if (!this.Store.TryGetRangeStartingWith(String8.Convert(prefix, new byte[String8.GetLength(prefix)]), out matchingWords)) return false;

            // Look for index matches for those words
            int[] matches;
            int matchesIndex, matchesCount;
            if (!this.Index.TryGetMatchesInRange(matchingWords, out matches, out matchesIndex, out matchesCount)) return false;

            // Get matches out until the match array is full (note, might include duplicates if a path contained multiple words with the prefix)
            for(int i = matchesIndex; i < matchesIndex + matchesCount; ++i)
            {
                if (resultIndices.IsFull) break;
                resultIndices.Add(matches[i]);
            }

            return true;
        }

        public void ReadBinary(BinaryReader r)
        {
            this.Store = new StringStore();
            this.Store.ReadBinary(r);

            this.Index = new MemberIndex();
            this.Index.ReadBinary(r);
        }

        public void WriteBinary(BinaryWriter w)
        {
            this.Index.ConvertToImmutable(this.Store);

            this.Store.WriteBinary(w);
            this.Index.WriteBinary(w);
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            PathFinder finder = new PathFinder();

            Console.WriteLine("Getting File Paths...");
            string[] filePaths = Directory.GetFiles(@"C:\Code\Conflux\src\elfie-arriba", "*.cs", SearchOption.AllDirectories);

            Console.WriteLine("Indexing...");
            finder.IndexPathWords(filePaths);

            string searchString = "Str";
            Console.WriteLine($"Searching for \"{searchString}\"...");

            // Allow up to 30 matches
            PartialArray<int> matches = new PartialArray<int>(30, true);
            finder.TryFind("Str", matches);
            for(int i = 0; i < matches.Count; ++i)
            {
                Console.WriteLine(filePaths[matches[i]]);
            }
        }
    }
}



-Scott

________________________________

**Comment by KirillOsenkov** [comment]
OMG thanks Scott, I'll check this out too!!
