### ISSUE TITLE
Consuming Elfie via NuGet?

### ISSUE THREAD

**Issue by KirillOsenkov** [Microsoft/elfie-arriba#173]
I've only found a very old unlisted package for Elfie used by Roslyn:
https://www.nuget.org/packages/Microsoft.CodeAnalysis.Elfie

Is there a newer NuGet package that I can consume that is published anywhere?

**Comment by vScottLouvau** [comment]
No, I’m not publishing versions of Elfie, so it’s just the source repo. I reference it from other projects via “git submodule reference”.

Also, my new project may be far enough along you can use this instead. We should meet up for lunch again. =)

-Scott

**Comment by KirillOsenkov** [comment]
OK I'll take you up on that offer soon!
