### ISSUE TITLE
What's Elfie package licence?

### ISSUE THREAD

**Issue by PawelSzczepanczyk** [Microsoft/elfie-arriba#201]
https://www.nuget.org/packages/Microsoft.CodeAnalysis.Elfie
We've been using the NuGet package in our project, but since it's been unlisted the licence info is gone and we don't know if we can still use it or not. Can you help?

**Comment by ScottLouvau** [comment]
Elfie is licensed under the MIT License at the root of the elfie-arriba repo. If you feel a copy is also needed in the Elfie folder, let me know and I'd be happy to put another copy there.

Sorry for the long delay in responding. I didn't have notifications correctly configured for issues in this repo. :/
